apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: xznvn1m6e-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-16250e4edd.rei4.p3.openshiftapps.com/rhtap/rhtap-qe:09456329e3ce53d66670648b653fd0f35f604900@sha256:9919d9de92048a48e969fcfc4a1364f7f14340776abb6080c8bf99c37977befa
        name: container-image  
